// <auto-generated />
namespace Coman3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddVideoLink : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddVideoLink));
        
        string IMigrationMetadata.Id
        {
            get { return "201605100248480_AddVideoLink"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
